from app.services.product_service import ProductService


async def create_products_cache():
    """Create products cache on redis"""
    products_seed = [
        {
            'price': 129.90,
            'image': 'https://image.com/prod1.png',
            'brand': 'whitelabel',
            'id': 1,
            'title': 'Fone de Ouvido Bluetooth',
            'reviewScore': 4,
        },
        {
            'price': 89.50,
            'image': 'https://image.com/prod2.png',
            'brand': 'techmax',
            'id': 2,
            'title': 'Mouse Gamer RGB',
            'reviewScore': 5,
        },
        {
            'price': 199.00,
            'image': 'https://image.com/prod3.png',
            'brand': 'mobitech',
            'id': 3,
            'title': 'Teclado Mecnico',
            'reviewScore': 4,
        },
        {
            'price': 59.90,
            'image': 'https://image.com/prod4.png',
            'brand': 'whitelabel',
            'id': 4,
            'title': 'Cabo USB-C Reforado',
            'reviewScore': 3,
        },
        {
            'price': 149.99,
            'image': 'https://image.com/prod5.png',
            'brand': 'eletron',
            'id': 5,
            'title': 'Carregador Turbo',
            'reviewScore': 4,
        },
        {
            'price': 289.00,
            'image': 'https://image.com/prod6.png',
            'brand': 'soundpro',
            'id': 6,
            'title': 'Caixa de Som Porttil',
            'reviewScore': 5,
        },
        {
            'price': 39.90,
            'image': 'https://image.com/prod7.png',
            'brand': 'whitelabel',
            'id': 7,
            'title': 'Pelcula Temperada',
            'reviewScore': 2,
        },
        {
            'price': 999.00,
            'image': 'https://image.com/prod8.png',
            'brand': 'visiontech',
            'id': 8,
            'title': 'Smartwatch Pro',
            'reviewScore': 4,
        },
        {
            'price': 79.99,
            'image': 'https://image.com/prod9.png',
            'brand': 'housefit',
            'id': 9,
            'title': 'Garrafa Trmica 1L',
            'reviewScore': 5,
        },
        {
            'price': 49.90,
            'image': 'https://image.com/prod10.png',
            'brand': 'kitchenpremium',
            'id': 10,
            'title': 'Kit Utenslios de Cozinha',
            'reviewScore': 3,
        },
        {
            'price': 1299.00,
            'image': 'https://image.com/prod11.png',
            'brand': 'visiontech',
            'id': 11,
            'title': 'Tablet 10.1" Wi-Fi',
            'reviewScore': 4,
        },
        {
            'price': 19.90,
            'image': 'https://image.com/prod12.png',
            'brand': 'whitelabel',
            'id': 12,
            'title': 'Suporte de Celular para Mesa',
            'reviewScore': 3,
        },
        {
            'price': 549.00,
            'image': 'https://image.com/prod13.png',
            'brand': 'soundpro',
            'id': 13,
            'title': 'Headset Gamer Surround',
            'reviewScore': 5,
        },
        {
            'price': 24.99,
            'image': 'https://image.com/prod14.png',
            'brand': 'whitelabel',
            'id': 14,
            'title': 'Cabo HDMI 2.1 2m',
            'reviewScore': 4,
        },
        {
            'price': 189.90,
            'image': 'https://image.com/prod15.png',
            'brand': 'eletron',
            'id': 15,
            'title': 'Power Bank 20000mAh',
            'reviewScore': 4,
        },
        {
            'price': 259.00,
            'image': 'https://image.com/prod16.png',
            'brand': 'mobitech',
            'id': 16,
            'title': 'Roteador Wi-Fi Dual Band',
            'reviewScore': 3,
        },
        {
            'price': 74.90,
            'image': 'https://image.com/prod17.png',
            'brand': 'housefit',
            'id': 17,
            'title': 'Kit Organizadores de Gaveta',
            'reviewScore': 5,
        },
        {
            'price': 399.00,
            'image': 'https://image.com/prod18.png',
            'brand': 'eletron',
            'id': 18,
            'title': 'Cmera de Segurana Wi-Fi',
            'reviewScore': 4,
        },
        {
            'price': 32.90,
            'image': 'https://image.com/prod19.png',
            'brand': 'whitelabel',
            'id': 19,
            'title': 'Lmpada LED Inteligente',
            'reviewScore': 4,
        },
        {
            'price': 219.00,
            'image': 'https://image.com/prod20.png',
            'brand': 'techmax',
            'id': 20,
            'title': 'Teclado Wireless Slim',
            'reviewScore': 3,
        },
    ]

    for item in products_seed:
        await ProductService.save_long_cache(item['id'], item)
